### ISSUE TITLE
didn't find &n_n_MOT error

### ISSUE THREAD

**Issue by ebergelson** [SeedlingsBabylab/parse_clan2#2]
parseclan2 missed finding a missing = sign in &n_n_MOT

**Comment by andreiamatuni** [comment]
It's finding it in my test cases. Are you sure it's not in the error file? The error should say something like this:

Ampersand Issue ("&" should be "&=")  line#: 1748  ['923310', '924350']  ['tummy &n_n_MOT']

**Comment by ebergelson** [comment]
weird, i'll retest later, but it definitely missed one in the initial
parse; i only found it when the numbers didn't match, i'll look into it on
monday.

_Elika Bergelson, PhD_
Research Assistant Professor, University of Rochester
Center for Language Sciences | Brain and Cognitive Science Dept. |
www.bcs.rochester.edu/people/ebergelson | www.bcs.rochester.edu/seedlings/
Get a signature like this: Click here!
http://ws-promos.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS9lbWFpbC1pbnN0YWxsP3dzX25jaWQ9NjcyMjk0MDA4JnV0bV9zb3VyY2U9ZXh0ZW5zaW9uJnV0bV9tZWRpdW09ZW1haWwmdXRtX2NhbXBhaWduPXByb21vXzU3MzI1Njg1NDg3Njk3OTIiLCAiZSI6ICI1NzMyNTY4NTQ4NzY5NzkyIn0=
