### ISSUE TITLE
double spaced excel output

### ISSUE THREAD

**Issue by URBabylab** [SeedlingsBabylab/parse_clan2#6]
Ran parse_clan_2 on a windows and it created an excel output like it was before with the words on every other line (blank space in the lines between).

**Comment by ebergelson** [comment]
are you sure you have the latest parseclan2 on that computer?

**Comment by URBabylab** [comment]
yep! updated it prior to running. I think this may be a windows only issue since no one has complained on the macs...

**Comment by andreiamatuni** [comment]
I just made some changes that might fix the problem. I don't have Windows on hand at the moment to test the fix, but it should work...
