### ISSUE TITLE
print # of lines to terminal

### ISSUE THREAD

**Issue by ebergelson** [SeedlingsBabylab/parse_clan2#8]
it'd be great if parseclan2 printed the number of words in the file to the terminal, e.g. how many rows there are not counting the header row

**Comment by andreiamatuni** [comment]
latest commit adds this

**Comment by ebergelson** [comment]
hm something's a little wrong
![screen shot 2015-09-14 at 6 07 04 pm](https://cloud.githubusercontent.com/assets/11085620/9863155/98e55b2e-5b0b-11e5-97f0-591e0892d141.png)
(19_11, terminal output from parseclan2 said 453 but parseclan2check correctly showed it was 459

**Comment by ebergelson** [comment]
(ignore my last comment I just deleted; I was wrong)
